### ISSUE TITLE
Linux location depends on install method used

### ISSUE THREAD

**Issue by poproar** [edwardbarnabas/Ardublock-standalone#5]
https://github.com/edwardbarnabas/Ardublock-standalone/blob/b1dc6722ada3e7d6d7ef8ca829ef72e5bdf18955/ardublock-all/src/main/java/com/ardublock/core/Context.java#L161

access users $HOME/arduino-1.8.12/
and check proper version install current is now .13 but our installer pulls v.12

**Comment by edwardbarnabas** [comment]
Got it!  I'll compile with $HOME/arduino-1.8.12/.. can you try it out?

**Comment by edwardbarnabas** [comment]
andrew is currently testing...

**Comment by edwardbarnabas** [comment]
playing with arduino-cli

Install:
curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/local/bin sh

**Comment by edwardbarnabas** [comment]
curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/dev/Ardublock-standalone sh
